# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
AWSTemplateFormatVersion: '2010-09-09'
Description: Template used for assumed IAM Roles for config validation (AwsAccount:LogArchive)

Parameters:
  pManagementAccountId:
    Type: String
  pRolePrefix:
    Type: String
    Default: lza-account-creation-     

Resources:
  rConfigLogValidationRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "This role will be assumed to create SSM Parameter based on AWS Account tags. 
              Role name is needed so that the role can be assumed."  
    Type: AWS::IAM::Role
    Properties:
      RoleName: config-log-validation
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:root
            Action:
              - sts:AssumeRole
            Condition:
              ArnLike:
                aws:PrincipalARN:
                  - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:role/${pRolePrefix}*              
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSConfigUserAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags:
        - Key: AccountCreationComponent
          Value: true
        - Key: CreatedBy
          Value: LZA_CustomizationConfig